Repository wecode-bootcamp-korea/14-2nd-SHABANG-frontend, pull requests merged in 2020-12, with the labels that each got.

#1 [14기 김동하] feature/Map 지도 기능 구현
  .eslintcache
  .gitignore
  package-lock.json
  public/data/beforeLevel6Positions.json
  public/images/apt-img.png
  public/index.html
  src/Config.js
  src/Pages/Apartment/Apartment.js
  src/Pages/Apartment/components/Map/MapContainer.js
  src/index.js
Labels: Status: 수정 요청

#5 [14기 장호철] 로그인 페이지 레이아웃, 카카오/구글 로그인 기능 추가
  .env
  .gitignore
  package-lock.json
  package.json
  public/images/emailBtn.png
  public/images/facebookBtn.png
  public/images/googleLogo.png
  public/images/kakaoLogo.png
  public/images/loginLogo.png
  public/images/naverBtn.png
  public/index.html
  src/Config.js
  src/Pages/LogIn/Component/LoginFooterBtn.js
  src/Pages/LogIn/LogIn.js
Labels: Status: Accepted

#8 [14기 장호철] 로그인 리팩토링 완료
  src/Pages/LogIn/Component/LoginFooterBtn.js
  src/Pages/LogIn/LogIn.js
Labels: Status: Accepted

#3 [14기 장호철] 주변시설 지도, 인포 윈도우 구현
  .gitignore
  package.json
  public/data/nearby.json
  public/images/icon.jpeg
  public/images/icon/arrow1.png
  public/images/icon/arrow2.png
  public/images/icon/cafeOff.png
  public/images/icon/cafeOn.png
  public/images/icon/closeBtn.png
  public/images/icon/rv_close.png
  public/images/icon/rv_open.png
  public/images/icon/schoolOff.png
  public/images/icon/schoolOn.png
  public/images/icon/storeOff.png
  public/images/icon/storeOn.png
  public/images/icon/subwayOff.png
  public/images/icon/subwayOn.png
  public/images/icon/subwayOn1.png
  shabangLogo.png
  src/Components/NearBy/Card/NearbyCard.js
  src/Components/NearBy/Card/NearbyMap.js
  src/Components/NearBy/Modal/Component/NearbyModalFooter.js
  src/Components/NearBy/Modal/Component/NearbyModalMocks.js
  src/Components/NearBy/Modal/NearbyModal.js
  src/Components/NearBy/NearBy.js
  src/Config.js
  src/Routes.js
  src/Styles/GlobalStyles.js
  src/index.js
Labels: Status: 리뷰 진행중

#2 [14기 엄문주] feature/OneRoom 지도 기능 구현
  .eslintcache
  .gitignore
  public/data/OneRoom.json
  public/images/Shabang.png
  public/images/blueprint.png
  public/images/question.png
  public/images/recommand.png
  public/index.html
  src/Config.js
  src/Pages/LogIn/LogIn.js
  src/Pages/OneRoom/Components/Map/Map.js
  src/Pages/OneRoom/Components/SearchBox/SearchBox.js
  src/Pages/OneRoom/Components/SideBar/SideBar.js
  src/Pages/OneRoom/Components/SideBarDetail/SideBarDetail.js
  src/Pages/OneRoom/OneRoom.js
  src/Routes.js
Labels: Status: 리뷰 요청

#4 [14기 김동하] feature/filter UI 및 기능 구현
  .eslintcache
  .eslintcache~14c7211... [add] 필터 기능 수정중 도움 요청
  package-lock.json
  package.json
  public/data/ButtonNameArray.js
  public/data/beforeLevel6Positions.json
  public/index.html
  src/Pages/Apartment/Apartment.js
  src/Pages/Apartment/components/.Filter.js.swp
  src/Pages/Apartment/components/Filter.js
  src/Pages/Apartment/components/FilterElement.js
  src/Pages/Apartment/components/Map/.MapContainer.js.swp
  src/Pages/Apartment/components/Map/MapContainer.js
Labels: Status: 리뷰 요청

#7 [14기 엄문주] NavBar 기능구현
  .gitignore
  .vscode/settings.json
  package-lock.json
  public/data/OneRoom.json
  public/images/shabang_logo.png
  public/index.html
  src/Components/NavBar/Dropdown.js
  src/Components/NavBar/DropdownAp.js
  src/Components/NavBar/DropdownNew.js
  src/Components/NavBar/DropdownOff.js
  src/Components/NavBar/DropdownOne.js
  src/Components/NavBar/DropdownVi.js
  src/Components/NavBar/NavBar.js
  src/Components/NavUnderBar/NavUnderApt.js
  src/Components/NavUnderBar/NavUnderOne.js
  src/Pages/OneRoom/OneRoom.js
  src/Routes.js
Labels: Status: 리뷰 요청

#9 [14기 엄문주] Nav바 기능 추가로 인해 다시 PR 요청 드립니다.
  src/Components/NavBar/NavBar.js
  src/Config.js
  src/Pages/LogIn/LogIn.js
  src/Pages/OneRoom/Components/Map/Map.js
  src/Pages/OneRoom/Components/SideBar/SideBar.js
  src/Pages/OneRoom/Components/SideBarDetail/SideBarDetail.js
  src/Pages/OneRoom/OneRoom.js
Labels: Status: Accepted

#11 [14기 장호철] 토큰 POST 방법 변경
  .eslintcache~14c7211... [add] 필터 기능 수정중 도움 요청
  .gitignore
  public/images/icon/subwayOn.png
  public/images/icon/subwayOn1.png
  src/Components/NearBy/Card/NearbyCard.js
  src/Components/NearBy/Modal/Component/NearbyModalFooter.js
  src/Components/NearBy/Modal/Component/NearbyModalMocks.js
  src/Components/NearBy/Modal/NearbyModal.js
  src/Config.js
Labels: Status: Accepted

#10 [14기 엄문주] OneRoom filter 기능 붙여서 다시 PR 올립니다.
  .eslintcache
  src/Components/NearBy/Card/NearbyCard.js
  src/Components/NearBy/Card/NearbyMap.js
  src/Components/NearBy/Modal/NearbyModal.js
  src/Config.js
  src/Pages/OneRoom/Components/Filter/Filter.js
  src/Pages/OneRoom/Components/Filter/FilterElement.js
  src/Pages/OneRoom/Components/SideBarDetail/SideBarDetail.js
  src/Pages/OneRoom/OneRoom.js
Labels: Status: Accepted

#12 [14기 엄문주] 갑작스러운 내용 수정으로 다시 PR 올립니다.
  src/Components/NavBar/Dropdown.js
  src/Components/NavBar/DropdownAp.js
  src/Components/NavBar/DropdownNew.js
  src/Components/NavBar/DropdownOff.js
  src/Components/NavBar/DropdownOne.js
  src/Components/NavBar/DropdownVi.js
  src/Components/NavBar/NavBar.js
  src/Components/NavUnderBar/NavUnderApt.js
  src/Components/NavUnderBar/NavUnderOne.js
  src/Config.js
  src/Pages/OneRoom/Components/SideBarDetail/SideBarDetail.js
Labels: Status: Accepted
